### ISSUE TITLE
Cannot build nor serve the site - Need to update README file

### ISSUE THREAD

**Issue by Haavi97** [juljus/VHKmatik-Website#1]
Running the command `npm run build` gives the following errror:

```
> vhkmatik-website@1.0.0 build
> . ./build.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
```

Also the information on how to use those commands should be added to the README file.

**Comment by juljus** [comment]
added info on how to build/serve the site to README.md

**Comment by juljus** [comment]
Issue was caused by not having z shell (the .sh files where run by using z shell). Switched to bash and updated requirements in README.md
