### ISSUE TITLE
Site Deployment

### ISSUE THREAD

**Issue by tenseoverflow** [juljus/VHKmatik-Website#4]
When the time comes, we need to deploy this static website. An option would be to deploy it to the school's server and automate it via GitHub's CD.

However, I'm more keen on going with Cloudflare Pages, which is free to use, has a good anycast network and works well with GitHub Actions. The drawback is, that it is off-site.

I also propose using the existing `vhk.ee` domain with a CNAME record like `matik.vhk.ee`, rather than buying a new domain.

**Comment by Haavi97** [comment]
Confirmed! We can used the subdomain. We just need the ip address once deployed.

**Comment by juljus** [comment]
The website is now live at: https://juljus.github.io/VHKmatik-Website/ (using github actions to deploy automatically when something is pushed to the main branch)
but thinks it is located at: https://juljus.github.io/ so it doesn't quite work yet

**Comment by tenseoverflow** [comment]
Alright, great! Totally forgot GitHub had its own static site hosting.

I think hosting GitHub Pages at their subdomain's root requires renaming the repository to `<yourusername>.github.io`. But with a custom domain, I don't think this is necessary.
